//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineExam.Areas.Admin.Admin_Resources.Admin_Resources", typeof(Admin_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string LblAccept {
            get {
                return ResourceManager.GetString("LblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string LblAction {
            get {
                return ResourceManager.GetString("LblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        public static string LblApprovalStatus {
            get {
                return ResourceManager.GetString("LblApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string LblChapter {
            get {
                return ResourceManager.GetString("LblChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check If Active.
        /// </summary>
        public static string LblCheckIfActive {
            get {
                return ResourceManager.GetString("LblCheckIfActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string LblEnddate {
            get {
                return ResourceManager.GetString("LblEnddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string LblEndtime {
            get {
                return ResourceManager.GetString("LblEndtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam.
        /// </summary>
        public static string LblExam {
            get {
                return ResourceManager.GetString("LblExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        public static string LblExamName {
            get {
                return ResourceManager.GetString("LblExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Type .
        /// </summary>
        public static string LblExamType {
            get {
                return ResourceManager.GetString("LblExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string LblFromDateTime {
            get {
                return ResourceManager.GetString("LblFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string LblIsActive {
            get {
                return ResourceManager.GetString("LblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Name.
        /// </summary>
        public static string LblLblChapterName {
            get {
                return ResourceManager.GetString("LblLblChapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Marked Fields Are Mandatory!.
        /// </summary>
        public static string LblMandatory {
            get {
                return ResourceManager.GetString("LblMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string LblNote {
            get {
                return ResourceManager.GetString("LblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing Marks.
        /// </summary>
        public static string LblPassingMarks {
            get {
                return ResourceManager.GetString("LblPassingMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string LblQuestion {
            get {
                return ResourceManager.GetString("LblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string LblReject {
            get {
                return ResourceManager.GetString("LblReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string LblSelectALl {
            get {
                return ResourceManager.GetString("LblSelectALl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string LblStartdate {
            get {
                return ResourceManager.GetString("LblStartdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string LblStarttime {
            get {
                return ResourceManager.GetString("LblStarttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LblTime {
            get {
                return ResourceManager.GetString("LblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile  Number.
        /// </summary>
        public static string LblUserMobileNumber {
            get {
                return ResourceManager.GetString("LblUserMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LblUserName {
            get {
                return ResourceManager.GetString("LblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Id.
        /// </summary>
        public static string LblUserRegistrationId {
            get {
                return ResourceManager.GetString("LblUserRegistrationId", resourceCulture);
            }
        }
    }
}
